# Generated by Django 3.2.6 on 2021-08-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=30)),
                ('first_name', models.CharField(blank=True, default='', max_length=60)),
                ('last_name', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.CharField(blank=True, default='', max_length=60)),
                ('username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
