# Generated by Django 3.2.6 on 2021-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=30),
        ),
    ]
