# Generated by Django 3.2.6 on 2021-08-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_alter_profiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Ms', 'Ms'), ('Mr.', 'Mr.')], max_length=30),
        ),
    ]
