# Generated by Django 3.2.6 on 2021-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_alter_profiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=30),
        ),
    ]
