# Generated by Django 3.2.6 on 2021-08-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0009_alter_profiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms', 'Ms'), ('Mrs.', 'Mrs.')], max_length=30),
        ),
    ]
