# Generated by Django 3.2.6 on 2021-08-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181101_2355'),
        ('products', '0009_alter_product_type'),
    ]

    operations = [
    ]
